# Generated by Django 6.0.7 on 2026-07-08 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('district', models.CharField(choices=[('Kathmandu', 'Kathmandu'), ('Lalitpur', 'Lalitpur'), ('Bhaktapur', 'Bhaktapur'), ('Kaski', 'Kaski'), ('Chitwan', 'Chitwan'), ('Butwal', 'Butwal'), ('Biratnagar', 'Biratnagar'), ('Birgunj', 'Birgunj'), ('Dharan', 'Dharan'), ('Hetauda', 'Hetauda'), ('Other', 'Other')], max_length=50)),
                ('address', models.TextField()),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
