# Generated by Django 4.2.29 on 2026-07-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_alter_hospitalprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
