# Generated by Django 4.2.30 on 2026-08-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='response',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Pending', max_length=10),
        ),
    ]
