# Generated by Django 6.1 on 2026-08-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='response',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined'), ('Completed', 'Completed'), ('Received', 'Received')], default='Pending', max_length=10),
        ),
    ]
