# Generated by Django 4.2.30 on 2026-07-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0004_alter_donorprofile_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorprofile',
            name='address',
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='ward',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
