# Generated by Django 4.2.30 on 2026-07-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0005_remove_donorprofile_address_donorprofile_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorprofile',
            name='municipality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
