# Generated by Django 4.2.30 on 2026-08-09 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0007_bloodrequest_units_fulfilled_and_more'),
        ('donors', '0006_alter_donorprofile_municipality'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='blood_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='blood_requests.bloodrequest'),
        ),
    ]
