# Generated by Django 6.0.7 on 2026-08-18 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0007_donation_blood_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_key', models.CharField(max_length=50)),
                ('badge_name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('claimed', models.BooleanField(default=True)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='donors.donorprofile')),
            ],
            options={
                'unique_together': {('donor', 'badge_key')},
            },
        ),
        migrations.AddField(
            model_name='donation',
            name='batch_code',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='destination_hospital',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('collected', 'Collected'), ('processing', 'Processing'), ('testing', 'Testing'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='collected', max_length=20),
        ),
    ]
