# Generated by Django 4.2.30 on 2026-07-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0004_alter_bloodrequest_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='municipality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='ward',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
