# Generated by Django 4.2.30 on 2026-07-24 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0006_alter_donorprofile_municipality'),
        ('blood_requests', '0005_bloodrequest_area_bloodrequest_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_requests', to='donors.donorprofile'),
        ),
    ]
