# Generated by Django 4.2.30 on 2026-08-09 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0006_bloodrequest_accepted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='units_fulfilled',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Fulfilled', 'Fulfilled')], default='Pending', max_length=10),
        ),
    ]
