# Generated by Django 4.2.30 on 2026-08-09 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0007_bloodrequest_units_fulfilled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='accepted_by',
        ),
    ]
